import * as Komunitas from "./Komunitas"
import * as Notification from "./Notification"
import * as Tracking from "./Tracking"
import * as Warung from "./Warung"
import * as Pedagang from "./Pedagang"
import * as MakComblang from "./MakComblang"

export { Komunitas, Notification, Tracking, Warung, Pedagang, MakComblang }
export { default as Loading } from "./Loading"
export { default as Splash } from "./Splash"
export { default as Login } from "./Login"
// export { default as Daftar } from "./Daftar"
// export { default as DaftarLanding } from "./DaftarLanding"
export { default as Dashboard } from "./Dashboard"
export { default as Success } from "./Success"
export * from "./LupaPassword"
export * from "./Daftar"
// export { default as DaftarStep } from "./Move"
export * from "./Resto"
export * from "./Profile"
